# -*- coding: utf-8 -*-
"""QR Code Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_gYBRB-fpLT8owXZiimIKucg69Zk04B
"""

!pip install qrcode[pil]

"""Import Libraries"""

import qrcode
from PIL import Image

"""Take User Input"""

data = input("Enter text or URL: ")

"""Create QR Object"""

qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_H,
    box_size=10,
    border=4
)

"""Add Data"""

qr.add_data(data)

"""Optimize"""

qr.make(fit=True)

"""Generate Image"""

'''img = qr.make_image(fill_color="black",
                    back_color="white")'''

#Costume Colors
img = qr.make_image(
    fill_color="pink",
    back_color="beige"
)

"""Save"""

img.save("QRCode.png")

"""Display"""

img

"""# QR CODE With Personalized LOGO


"""

!pip install qrcode[pil]

import qrcode
from PIL import Image


# User Input
data = input("Enter text or URL: ")

#Image for Logo
from google.colab import files
uploaded = files.upload()

logo_path = list(uploaded.keys())[0]

print("Uploaded:", logo_path)

# Create QR Code
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_H,   # High error correction
    box_size=10,
    border=4
)

qr.add_data(data)
qr.make(fit=True)

img = qr.make_image(
    fill_color="pink",
    back_color="white"
).convert("RGB")


# Load Logo
logo = Image.open(logo_path).convert("RGBA")

# Resize logo
qr_width, qr_height = img.size

logo_size = qr_width // 5      # Logo = 20% of QR width

logo = logo.resize((logo_size, logo_size))

# Position logo at center
x = (qr_width - logo_size) // 2
y = (qr_height - logo_size) // 2

# Paste logo
img.paste(logo, (x, y), mask=logo if logo.mode == "RGBA" else None)

# Save
img.save("QR_with_logo.png")

print("QR Code Generated Successfully!")

img

